export default {
  id: '07-trading-strategies',
  title: 'Trading Strategies',
  icon: '🎯',
  colorHex: '#22c55e',
  description: 'Build and deploy intraday, options, swing, and multi-agent trading strategies for Indian markets.',
  difficulty: 'advanced',
  estimatedHours: 6,
  prerequisites: ['05-technical-indicators', '06-order-flow'],
  chapters: [
    {
      id: 'c1-intraday',
      title: 'Intraday Strategies',
      description: 'Scalp and day-trade Nifty and BankNifty with proven intraday setups.',
      estimatedMinutes: 55,
      sections: [
        { id: 's1-orb', title: 'Opening Range Breakout', difficulty: 'advanced', readingMinutes: 15, description: 'ORB strategy for Nifty/BankNifty at 9:15 open.' },
        { id: 's2-vwap-reversion', title: 'VWAP Reversion', difficulty: 'advanced', readingMinutes: 12, description: 'Mean reversion trades around VWAP levels.' },
        { id: 's3-momentum-scalping', title: 'Momentum Scalping', difficulty: 'advanced', readingMinutes: 12, description: 'Scalping with order flow momentum confirmation.' },
        { id: 's4-gap-trading', title: 'Gap Trading (NSE Open)', difficulty: 'advanced', readingMinutes: 12, description: 'Trade gap-up and gap-down opens at NSE.' },
      ],
    },
    {
      id: 'c2-options-strategies',
      title: 'Options Strategies (Nifty/BankNifty)',
      description: 'Trade weekly options with straddles, condors, and gamma scalping.',
      estimatedMinutes: 55,
      sections: [
        { id: 's1-straddle-strangle', title: 'Straddle & Strangle Selling', difficulty: 'advanced', readingMinutes: 15, description: 'Weekly expiry straddle/strangle selling strategies.' },
        { id: 's2-iron-condor', title: 'Iron Condor & Butterfly', difficulty: 'advanced', readingMinutes: 12, description: 'Range-bound strategies with defined risk.' },
        { id: 's3-calendar-diagonal', title: 'Calendar & Diagonal Spreads', difficulty: 'advanced', readingMinutes: 12, description: 'Time decay strategies across expiries.' },
        { id: 's4-gamma-scalping', title: 'Gamma Scalping', difficulty: 'advanced', readingMinutes: 15, description: 'Dynamic delta hedging and gamma scalping.' },
      ],
    },
    {
      id: 'c3-swing-positional',
      title: 'Swing & Positional',
      description: 'Multi-day strategies using sector rotation, pairs, and events.',
      estimatedMinutes: 55,
      sections: [
        { id: 's1-multi-timeframe', title: 'Multi-Timeframe Analysis', difficulty: 'advanced', readingMinutes: 15, description: 'Align signals across daily, 4H, and 1H charts.' },
        { id: 's2-sector-rotation', title: 'Sector Rotation Strategies', difficulty: 'advanced', readingMinutes: 12, description: 'Rotate between Indian market sectors.' },
        { id: 's3-pairs-trading', title: 'Pairs Trading (Indian Stocks)', difficulty: 'advanced', readingMinutes: 15, description: 'Statistical pairs trading with cointegrated stocks.' },
        { id: 's4-event-driven', title: 'Event-Driven (Earnings, RBI Policy)', difficulty: 'advanced', readingMinutes: 12, description: 'Trade around earnings, RBI policy, and elections.' },
      ],
    },
    {
      id: 'c4-derivatives-delta',
      title: 'Derivatives Strategies (Delta Exchange)',
      description: 'Trade crypto derivatives on Delta Exchange with basis and vol strategies.',
      estimatedMinutes: 55,
      sections: [
        { id: 's1-basis-trading', title: 'Crypto Futures Basis Trading', difficulty: 'advanced', readingMinutes: 15, description: 'Cash-and-carry arbitrage on Delta Exchange.' },
        { id: 's2-funding-rate', title: 'Perpetual Funding Rate Arbitrage', difficulty: 'advanced', readingMinutes: 12, description: 'Harvest funding rates on perpetual contracts.' },
        { id: 's3-vol-strategies', title: 'Options Volatility Strategies', difficulty: 'advanced', readingMinutes: 12, description: 'Trade crypto implied volatility on Delta.' },
        { id: 's4-cross-exchange', title: 'Cross-Exchange Arbitrage', difficulty: 'advanced', readingMinutes: 15, description: 'Arbitrage opportunities across exchanges.' },
      ],
    },
    {
      id: 'c5-multi-agent',
      title: 'Multi-Agent Trading',
      description: 'Deploy AI agents that analyze, debate, and trade autonomously.',
      estimatedMinutes: 55,
      sections: [
        { id: 's1-analyst-agents', title: 'Analyst Agents (Technical, Fundamental, Sentiment)', difficulty: 'advanced', readingMinutes: 15, description: 'Build specialized analyst agents with Claude.' },
        { id: 's2-bull-bear-debate', title: 'Bull/Bear Debate Framework', difficulty: 'advanced', readingMinutes: 12, description: 'Structure debates between bull and bear agents.' },
        { id: 's3-risk-agents', title: 'Risk Management Agents', difficulty: 'advanced', readingMinutes: 12, description: 'Aggressive, conservative, and neutral risk agents.' },
        { id: 's4-portfolio-manager', title: 'Portfolio Manager Agent', difficulty: 'advanced', readingMinutes: 15, description: 'Final approval agent for trade execution.' },
      ],
    },
    {
      id: 'c6-strategy-combination',
      title: 'Strategy Combination',
      description: 'Combine multiple strategies with signal aggregation and regime detection.',
      estimatedMinutes: 55,
      sections: [
        { id: 's1-signal-aggregation', title: 'Signal Aggregation & Scoring', difficulty: 'advanced', readingMinutes: 15, description: 'Score and aggregate signals from multiple strategies.' },
        { id: 's2-regime-detection', title: 'Regime Detection & Strategy Switching', difficulty: 'advanced', readingMinutes: 12, description: 'Detect market regimes and switch strategies.' },
        { id: 's3-risk-allocation', title: 'Portfolio-Level Risk Allocation', difficulty: 'advanced', readingMinutes: 12, description: 'Allocate risk budget across strategies.' },
        { id: 's4-drawdown-management', title: 'Drawdown Management', difficulty: 'advanced', readingMinutes: 15, description: 'Manage drawdowns and recovery procedures.' },
      ],
    },
  ],
}
